name: Static code analysis and Unit test

on:
   push:
     branches:
       - main
   pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.3.0
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdatabase
    env:
      DB_CONNECTION: mysql
      DB_READ_HOSTS: 127.0.0.1
      DB_WRITE_HOSTS: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testdatabase
      DB_USERNAME: root
      DB_PASSWORD: password
      PHP_VERSION: '8.3'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache vendor directory
        id: cache
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Composer dump autoload
        run: composer dump-autoload
      - name: Generate key
        run: php artisan key:generate --env=testing
      - name: Execute phpstan
        run: ./vendor/bin/phpstan analyse
      - name: Migrate
        run: php artisan migrate --env=testing
      - name: Execute test
        run: ./vendor/bin/phpunit
